[window]
dynamic_title = false

[font]
normal = { family = "JetBrainsMono NF Light" }
size = 13
# normal = { family = "Fira Code Light" }
# size = 13
# normal = { family = "Berkeley Mono Light" }
# size = 14
# normal = { family = "VictorMono Nerd Font", style = "bold" }
# size = 14

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "On" }
unfocused_hollow = false
thickness = 0.15

[[hints.enabled]]
regex = "[^ ]+\\.rs:\\d+:\\d+"
command = { program = "code", args = ["--goto"] }
mouse = { enabled = true }

[env]
term = "xterm-256color"

[general]
import = ["~/.config/alacritty/tokyo-night.toml"]
